"""fix UserRole (add student role)

Revision ID: 2fdc9b058c41
Revises: 371657ef685d
Create Date: 2026-09-21 16:02:39.437240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "2fdc9b058c41"
down_revision: Union[str, Sequence[str], None] = "371657ef685d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="userrole",
        new_values=["admin", "parent", "student", "tutor"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="users", column_name="role"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(  # type: ignore
        enum_schema="public",
        enum_name="userrole",
        new_values=["parent", "tutor", "admin"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="users", column_name="role"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
